add Slack error handling and remove use of deprecated API method
m3dev/gokart pull request #141
Opened 2020-09-13 05:54 UTC by hirosassa

## What is this PR?

fixes #111 

I implemented following features:

1. error handling and ignoring of `SlackApiError` and `ChannelNotFoundError`
2. remove deprecated API method: `channels.list` and simplify pagination handling

2020-09-13 05:55 UTC, hirosassa commented
@vaaaaanquish @Hi-king Plz review!

2020-09-13 08:45 UTC, hirosassa commented on gokart/slack/slack_api.py
> +            for channels in self._client.conversations_list(params=params):
Thanks to [SlackResponse](https://github.com/slackapi/python-slackclient/blob/main/slack/web/slack_response.py), it has __next__ methond, we can remove redundant lines of 
code for pagination handling.

2020-09-13 08:47 UTC, hirosassa commented on gokart/slack/slack_api.py
> +            logger.warning(f'The job will start without slack notification: {e}')
ignoring error, because slack notification is an nice-to-have feature

2020-09-13 08:48 UTC, hirosassa commented on test/slack/test_slack_api.py
> +                     'The job will start without slack notification: Channel test is not found in public channels.'))
`LogCapture` enables testing log outputs

2020-09-13 08:49 UTC, hirosassa commented on test/slack/test_slack_api.py
> +def _slack_response(token, data):
helper function for generating SlackResponse

2020-09-14 05:47 UTC, vaaaaanquish commented
LGTM. Great unittests:)

2020-09-14 06:10 UTC, Hi-king commented on gokart/slack/README.md
> +# goakrt Slack notification
```suggestion
# gokart Slack notification
```
😸

2020-09-14 06:12 UTC, Hi-king commented
@hirosassa How about separating docs from code. My suggestion is moving gokart/slack/README.md to docs/slack.md.

2020-09-14 06:18 UTC, Hi-king requested changes
Need a little bit more discussion about where to put docs :)

2020-09-14 06:24 UTC, hirosassa commented on gokart/slack/README.md
> +# goakrt Slack notification
Oh! Thanks for your suggestion!

2020-09-14 06:47 UTC, Hi-king commented
And I found that all docs in `docs` directory are rst formatted :)

2020-09-14 08:51 UTC, hirosassa commented
> My suggestion is moving gokart/slack/README.md to docs/slack.md.
@Hi-king 
I agree with your idea. I rewrite the document on rst format!

2020-09-14 09:09 UTC, Hi-king approved these changes

2020-09-14 09:10 UTC, Hi-king commented
@hirosassa thanks!

2020-09-14 09:10 UTC, merged