added option to cache_unique_id
m3dev/gokart pull request #213
Opened 2021-06-12 17:51 UTC by TaylerUva

added option to cache_unique_id
maintains backwards compatibility
fixes #210

2021-06-12 18:17 UTC, vaaaaanquish commented
@TaylerUva Thx. 🆒 
Can you write unittest?

2021-06-12 19:44 UTC, hirosassa commented
Thanks for your contribution!
Your change looks good.
Please fix formatting, and add UT for this change.

2021-06-13 14:50 UTC, hirosassa requested changes
Thanks for your rapid response!
I added a comment.

2021-06-13 16:07 UTC, TaylerUva commented on .gitignore
> +**/.DS_Store
I can see your point with not adding .vscode to gitignore. However I believe ignoring operating system files is pretty standard and should be implemented. I would even suggest ignoring standard os files for all operating systems.

[example os gitignore generated from gitignore.io](https://www.toptal.com/developers/gitignore/api/windows,macos,linux)

2021-06-13 16:15 UTC, TaylerUva commented on .gitignore
> +**/.DS_Store
Did some research on this topic and I agree now. Thanks for the feedback!

2021-06-13 20:50 UTC, hirosassa commented
Looks great! Thank you @TaylerUva !

2021-06-13 20:50 UTC, hirosassa approved these changes

2021-06-14 12:09 UTC, vaaaaanquish commented
Thanks. 🆒

2021-06-14 12:09 UTC, vaaaaanquish approved these changes

2021-06-14 12:19 UTC, Hi-king approved these changes

2021-06-14 12:19 UTC, Hi-king commented on test/test_cache_unique_id.py
> +        self.assertNotEqual(output1, output2)
Comprehensive tests! 🆒

2021-06-14 12:21 UTC, merged

2021-06-14 12:21 UTC, Hi-king commented
Merged! Thx for your great contribution @TaylerUva 

And for reviews @vaaaaanquish @hirosassa