add indexedfeather file processor
m3dev/gokart pull request #223
Opened 2021-07-11 09:31 UTC by mski-iksm

[What?]
I've added indexed feather file processor which is capable to store index data.

[Why?]
The existing FeatherFileProcessor cannot save index information since the index must be 0,1,2,.... when saving as feather.

Please review.
@Hi-king @hirosassa @vaaaaanquish @e-mon

2021-07-11 09:51 UTC, hirosassa commented
Looks good!

2021-07-11 09:51 UTC, hirosassa approved these changes

2021-07-11 10:12 UTC, vaaaaanquish commented
Is there any reason why reset_index should not be used?

I think the code is good, but there is no additional documentation and I don't know the usage scenarios.

2021-07-11 10:13 UTC, vaaaaanquish requested changes
Add documents and ut

2021-07-11 11:35 UTC, mski-iksm commented
@vaaaaanquish 

> Is there any reason why reset_index should not be used?
> 
> I think the code is good, but there is no additional documentation and I don't know the usage scenarios.

If you have feather file which is dumped with FeatherFileProcessor and index processed with reset_index(), there is no way to know which column was index originally.
Using IndexedFeatherFileProcessor
- when dump(): index will converted to a column with certain prefix on the name
- when load(): a column with certain prefix on the name will be restored as index

By this behavior, you can use IndexedFeatherFileProcessor as like other FileProcessor without considering about index problem.

2021-07-11 12:19 UTC, vaaaaanquish commented
@mski-iksm I know how it works. But I can't think of a situation where more than two Tasks need `index` . Since indexing of pandas is not stable (implicit reset, pandas version,...and more), it is better to use column as the basic method for merging, grouping, ...


There are two reasons why I am cautious about this approach
- It's trying to force implementation of features that are sufficient for column.
- Adding the original extension will confuse the user > `.indexedfeather`

2021-07-11 12:20 UTC, vaaaaanquish commented
For example, can we consider extending the existing FeatherFileProcessor?

2021-07-11 15:07 UTC, mski-iksm commented
@vaaaaanquish 
>For example, can we consider extending the existing FeatherFileProcessor?

Yes, I will
- move index processing codes to FeatherFileProcessor, and remove IndexedFeatherFileProcessor
- add option to FeatherFileProcessor whether to process the index or not
- add note of FeatherFileProcessor about the index processing option to docs

2021-07-22 02:42 UTC, mski-iksm commented
@Hi-king @vaaaaanquish 
I've added test and docs. Please review!

2021-07-22 05:01 UTC, vaaaaanquish commented on docs/task_on_kart.rst
> +    If you don't prefere saving index, set `store_index_in_feather=False` parameter at `gokart.target.make_target()`.
🆒

2021-07-22 05:01 UTC, vaaaaanquish approved these changes

2021-07-22 05:07 UTC, hirosassa commented on docs/task_on_kart.rst
> +    If you don't prefere saving index, set `store_index_in_feather=False` parameter at `gokart.target.make_target()`.
👍 +1:

2021-07-26 13:01 UTC, mski-iksm commented
@hirosassa @vaaaaanquish Thank you for reviewing! I'll merge this PR.

2021-07-26 13:01 UTC, merged