Use cache in make task info
m3dev/gokart pull request #283
Opened 2022-04-27 11:34 UTC by ujiuji1259

I've added the `cache` argument to `make_task_info_tree` to use cache in making TaskInfo tree.

This reduces time to make TaskInfo tree especially when the task tree is large.

2022-04-27 11:54 UTC, hirosassa requested changes
Thanks for your contribution! I added a small comment, but almost LGTM

2022-04-27 11:54 UTC, hirosassa commented on gokart/tree/task_info_formatter.py
> +
[nits] redundant line

2022-04-27 12:32 UTC, hirosassa approved these changes
LGTM!

2022-05-04 15:23 UTC, mski-iksm commented
@ujiuji1259 LGTM!

2022-05-04 15:24 UTC, mski-iksm approved these changes

2022-05-06 08:06 UTC, Hi-king commented
@ujiuji1259 Thx for your contribution, @mski-iksm @hirosassa thx for reviews :)

2022-05-06 08:06 UTC, merged