Added should_dump_supplementary_log_files option
m3dev/gokart pull request #291
Opened 2022-07-02 06:16 UTC by mski-iksm

[What]
TaskOnKart.should_dump_supplementary_log_files is an option to control whether to dump supplementary files (task_log, random_seed, task_params, processing_time, module_versions) or not. Default is True, which means to dump as before.

[Why]
When each task runs, they will make 1 or more output files as defined in task.run(). Besides, 5 supplementary files (task_log, random_seed, task_params, processing_time, module_versions) will also be dumped. 
When using cloud data storage and running a large number of tasks, number of files will affect the price for data processing. This option will skip the dumping process of supplementary files to keep the price low.

2022-07-02 21:10 UTC, hirosassa requested changes
Your changes looks good!

Please document this feature.
https://github.com/m3dev/gokart/blob/master/docs/task_on_kart.rst

2022-07-04 05:01 UTC, mski-iksm commented
@hirosassa Thanks for the comment. I've added a document!

2022-07-04 13:12 UTC, hirosassa approved these changes
LGTM!

2022-07-04 23:58 UTC, kitagry approved these changes
LGTM

2022-07-05 00:48 UTC, merged

2022-07-05 00:48 UTC, hirosassa commented
@mski-iksm Thanks again for your contribution!